const categorias = [
  {
    aromaticas: [
      {
        id: 1,
        producto: "Albahaca",
        codigo_de_barras: "#¡VALOR!",
        codigo: 4,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/ALBAHACA16AGOSTO2023.webp",
      },
      {
        id: 2,
        producto: "Albahaca Violeta",
        codigo_de_barras: "#¡VALOR!",
        codigo: 5,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/ALBAHACA VIOLETA 2024.webp",
      },
      {
        id: 3,
        producto: "Apio",
        codigo_de_barras: "#¡VALOR!",
        codigo: 10,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/APIO 19 ENERO 2021.webp",
      },
      {
        id: 4,
        producto: "Cilantro",
        codigo_de_barras: "#¡VALOR!",
        codigo: 65,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/CILANTRO ENERO 2024.webp",
      },
      {
        id: 5,
        producto: "Eneldo",
        codigo_de_barras: "#¡VALOR!",
        codigo: 95,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/ENELDO DIC 2020.webp",
      },
      {
        id: 6,
        producto: "Hinojo",
        codigo_de_barras: "#¡VALOR!",
        codigo: 162,
        precio: 30.0,
        imagen: "../assets/categorias/aromaticas/HINOJO ENERO 2024.webp",
      },
      {
        id: 7,
        producto: "Manzanilla",
        codigo_de_barras: "#¡VALOR!",
        codigo: 32,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/MANZANILLA 13OCT2022.webp",
      },
      {
        id: 8,
        producto: "Melissa",
        codigo_de_barras: "#¡VALOR!",
        codigo: 183,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/MELISSA 13 OCTUBRE 2022.webp",
      },
      {
        id: 9,
        producto: "Menta",
        codigo_de_barras: "#¡VALOR!",
        codigo: 186,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/MENTA 16 AGOSTO 2023.webp",
      },
      {
        id: 10,
        producto: "Mix de plantas aromaticas",
        codigo_de_barras: "#¡VALOR!",
        codigo: 410,
        precio: 37.0,
        imagen:
          "../assets/categorias/aromaticas/MIX DE PLANTAS AROMATICAS.webp",
      },
      {
        id: 11,
        producto: "Mix de plantas para infusiones",
        codigo_de_barras: "#¡VALOR!",
        codigo: 408,
        precio: 37.0,
        imagen:
          "../assets/categorias/aromaticas/MIX DE PLANTAS PARA INFUSIONES.webp",
      },
      {
        id: 12,
        producto: "Oregano",
        codigo_de_barras: "#¡VALOR!",
        codigo: 194,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/OREGANO ENERO 2024.webp",
      },
      {
        id: 13,
        producto: "Perejil",
        codigo_de_barras: "#¡VALOR!",
        codigo: 207,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/PEREJIL 05JUNIO2023.webp",
      },
      {
        id: 14,
        producto: "Romero",
        codigo_de_barras: "#¡VALOR!",
        codigo: 263,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/ROMERO MARZO 2023.webp",
      },
      {
        id: 15,
        producto: "Tomillo",
        codigo_de_barras: "#¡VALOR!",
        codigo: 275,
        precio: 22.0,
        imagen: "../assets/categorias/aromaticas/TOMILLO 01MARZO2024.webp",
      },
    ],

    bulbos: [
      {
        id: 1,
        producto: "BOLSA DE 5 BULBOS DE CALLA LILY",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 416,
        precio: 75.0,
        imagen: "../assets/categorias/bulbos/5 BULBOS CALLA LILY.webp",
      },
    ],

    cesped: [
      {
        id: 1,
        producto: "BERMUDA GRASS",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 292,
        precio: 130.0,
        imagen: "../assets/categorias/cesped/CESPED BERMUDA-CLIMA CALIDO.webp",
      },
      {
        id: 2,
        producto: "GRAMA 25g",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 297,
        precio: 30.0,
        imagen: "../assets/categorias/cesped/GRAMA 25 g ENERO 2024.webp",
      },
      {
        id: 3,
        producto: "GRAMA COMPETENCIA DEPORTIVA 1k",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 302,
        precio: 225.0,
        imagen:
          "../assets/categorias/cesped/GRAMA COMPETENCIA DEPORTIVA 1 kg 11 01 2022.webp",
      },
      {
        id: 4,
        producto: "GRAMA PARA SOMBRA",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 431,
        precio: 82.0,
        imagen: "../assets/categorias/cesped/CESPED PARA SOMBRA.webp",
      },
    ],

    hortalizas: [
      {
        id: 1,
        producto: "Acelga",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 1,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/ACELGA MAYO 2020.webp",
      },
      {
        id: 2,
        producto: "Alcachofa",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 6,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/ALCACHOFA 30 MARZO 2022.webp",
      },
      {
        id: 3,
        producto: "Amaranto",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 386,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/AMARANTO 05102015.webp",
      },
      {
        id: 4,
        producto: "Arugula",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 368,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/ARUGULA 19 OCTUBRE 2021.webp",
      },
      {
        id: 5,
        producto: "Berenjena",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 16,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/BERENJENA 14062016.webp",
      },
      {
        id: 6,
        producto: "Berro de Agua",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 17,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/BERRO DE AGUA DIC 2020.webp",
      },
      {
        id: 7,
        producto: "Brocoli",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 372,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/BROCOLI 30 MARZO 2022.webp",
      },
      {
        id: 8,
        producto: "Calabacin",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 20,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/CALABACIN 16 AGOSTO 2023.webp",
      },
      {
        id: 9,
        producto: "Cebolla blanca",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 34,
        precio: 30.0,
        imagen:
          "../assets/categorias/hortalizas/CEBOLLA BLANCA 16 AGOSTO 2023.webp",
      },
      {
        id: 10,
        producto: "Cebolla Roja",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 42,
        precio: 30.0,
        imagen:
          "../assets/categorias/hortalizas/CEBOLLA ROJA 05 MAYO 2022.webp",
      },
      {
        id: 11,
        producto: "Cebollin",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 46,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/CEBOLLIN 01MARZO2024.webp",
      },
      {
        id: 12,
        producto: "Chile Jalapeño",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 55,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/JALAPEÑO 5JUNIO2023.webp",
      },
      {
        id: 13,
        producto: "Chile Peperone Picante-CAYENNE",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 60,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/CHILE CAYENNE 13 OCTUBRE 2022.webp",
      },
      {
        id: 14,
        producto: "Chile Pimiento Corto",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 216,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/PIMIENTO CORTO 2 OCT 2023.webp",
      },
      {
        id: 15,
        producto: "Chile Pimiento Largo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 222,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/PIMIENTO LARGO ENERO 2024.webp",
      },
      {
        id: 16,
        producto: "Chile Sigarreta",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 62,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/CHILE SIGARRETA.webp",
      },
      {
        id: 17,
        producto: "Chipilin",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 385,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/CHIPILIN 13 OCTUBRE 2022.webp",
      },
      {
        id: 18,
        producto: "Col de Bruselas",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 81,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/COL DE BRUSELAS SEPT 2020.webp",
      },
      {
        id: 19,
        producto: "Col de Milan",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 80,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/COL.webp",
      },
      {
        id: 20,
        producto: "Coliflor",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 84,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/COLIFLOR 2024.webp",
      },
      {
        id: 21,
        producto: "Esparrago",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 98,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/ESPARRAGO 13 OCTUBRE 2022.webp",
      },
      {
        id: 22,
        producto: "Espinaca",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 100,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/ESPINACA MARZO 2023.webp",
      },
      {
        id: 23,
        producto: "Fresa",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 129,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/FRESA 16 AGOSTO 2023.webp",
      },
      {
        id: 24,
        producto: "Frijol Ejotero",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 276,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/EJOTE FEBRERO 2023.webp",
      },
      {
        id: 25,
        producto: "Guisante",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 145,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/GUISANTE 19 ENERO 2021.webp",
      },
      {
        id: 26,
        producto: "Haba",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 152,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/HABA.webp",
      },
      {
        id: 27,
        producto: "Hierbamora",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 161,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/HIERBAMORA ENERO 2024.webp",
      },
      {
        id: 28,
        producto: "Jamaica",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 388,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/JAMAICA ENERO 2024.webp",
      },
      {
        id: 29,
        producto: "Lechuga",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 171,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/LECHUGA 13 OCTUBRE 2022.webp",
      },
      {
        id: 30,
        producto: "Lechuga Roja",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 176,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/LECHUGA ROJA 19JULIO2021.webp",
      },
      {
        id: 31,
        producto: "Lechuga Romana",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 166,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/LECHUGA ROMANA 29JUNIO 2022.webp",
      },
      {
        id: 32,
        producto: "Maiz Dulce",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 179,
        precio: 37.0,
        imagen: "../assets/categorias/hortalizas/MAIZ DULCE 9 ABRIL 2021.webp",
      },
      {
        id: 33,
        producto: "Melon",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 184,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/MELON 18AGOSTO 2022.webp",
      },
      {
        id: 34,
        producto: "Mezcla de Ensaladas",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 188,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/MEZCLA DE ENSALADAS 29JUNIO 2022.webp",
      },
      {
        id: 35,
        producto: "Mezcla de Hierbas p/C",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 189,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/MEZCLA DE HIERBAS PARA COCINAR.webp",
      },
      {
        id: 36,
        producto: "Miltomate",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 274,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/MILTOMATE 18AGOSTO 2022.webp",
      },
      {
        id: 37,
        producto: "Mix de hortalizas para semilleros",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 407,
        precio: 37.0,
        imagen:
          "../assets/categorias/hortalizas/MEZCLA DE HORTALIZAS PARA SEMILLEROS.webp",
      },
      {
        id: 38,
        producto: "Mix de hortalizas para siembra directa",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 409,
        precio: 37.0,
        imagen:
          "../assets/categorias/hortalizas/MEZCLA DE SEMILLAS PARA SIEMBRA DIRECTA ENERO 2024.webp",
      },
      {
        id: 39,
        producto: "Mix de plantas para chirmol/Salsa Roja",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 412,
        precio: 37.0,
        imagen: "../assets/categorias/hortalizas/MEZCLA SALSA ROJA.webp",
      },
      {
        id: 40,
        producto: "Mix de Plantas para chirmol/Salsa Verde",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 413,
        precio: 37.0,
        imagen: "../assets/categorias/hortalizas/MEZCLA SALSA VERDE.webp",
      },
      {
        id: 41,
        producto: "Mix de plantas para salsa picante",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 411,
        precio: 37.0,
        imagen: "../assets/categorias/hortalizas/MEZCLA DE SALSA PICANTE.webp",
      },
      {
        id: 42,
        producto: "Mostaza",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 369,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/MOSTAZA.webp",
      },
      {
        id: 43,
        producto: "Nabo Blanco",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 192,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/NABO SEPT 2020.webp",
      },
      {
        id: 44,
        producto: "Okra",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 193,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/OKRA.webp",
      },
      {
        id: 45,
        producto: "Pepino",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 202,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/PEPINO MARZO 2 2021.webp",
      },
      {
        id: 46,
        producto: "Puerro",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 228,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/PUERRO ENERO 2024.webp",
      },
      {
        id: 47,
        producto: "Rabano",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 233,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/RABANO ENERO 2024.webp",
      },
      {
        id: 48,
        producto: "Remolacha",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 252,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/REMOLACHA 9 ABRIL 2021.webp",
      },
      {
        id: 49,
        producto: "Repollo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 257,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/REPOLLO 29JUNIO 2022.webp",
      },
      {
        id: 50,
        producto: "Repollo Rojo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 262,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/REPOLLO ROJO.webp",
      },
      {
        id: 51,
        producto: "Sandia Larga",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 268,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/SANDIA LARGA FEBRERO 2023.webp",
      },
      {
        id: 52,
        producto: "Sandia Redonda",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 267,
        precio: 22.0,
        imagen:
          "../assets/categorias/hortalizas/SANDIA CRIMSON SWEET FEBRERO 2023.webp",
      },
      {
        id: 53,
        producto: "Tomate Largo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 272,
        precio: 30.0,
        imagen: "../assets/categorias/hortalizas/TOMATE LARGO ENERO 2024.webp",
      },
      {
        id: 54,
        producto: "Tomate Redondo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 271,
        precio: 37.0,
        imagen:
          "../assets/categorias/hortalizas/TOMATE REDONDO 5JUNIO2023.webp",
      },
      {
        id: 55,
        producto: "Zanahoria Berlicum",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 286,
        precio: 22.0,
        imagen: "../assets/categorias/hortalizas/ZANAHORIA 2 OCT 2023.webp",
      },
    ],

    ornamentales: [
      {
        id: 1,
        producto: "Aleli",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 8,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ALELI 13 OCTUBRE 2022.webp",
      },
      {
        id: 2,
        producto: "Antirrino",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 9,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ANTIRRINO SEPT 2020.webp",
      },
      {
        id: 3,
        producto: "Cactus",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 19,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CACTUS 13 OCTUBRE 2022.webp",
      },
      {
        id: 4,
        producto: "Calendula",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 30,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CALENDULA 19 ENERO 2021.webp",
      },
      {
        id: 5,
        producto: "Campanula",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 31,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CAMPANULA 19JULIO2021.webp",
      },
      {
        id: 6,
        producto: "Capuchina",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 33,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CAPUCHINA 29JUNIO 2022.webp",
      },
      {
        id: 7,
        producto: "Celosia Plumosa",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 52,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CELOSIA PLUMOSA 19 ENERO 2021.webp",
      },
      {
        id: 8,
        producto: "Centaurea",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 53,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CENTAUREA JUNIO 2020.webp",
      },
      {
        id: 9,
        producto: "Cipress Piramidal",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 429,
        precio: 37.0,
        imagen:
          "../assets/categorias/ornamentales/CIPRES PIRAMIDAL 24 ABRIL 2023.webp",
      },
      {
        id: 10,
        producto: "Clavel Amarillo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 72,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CLAVEL AMARILLO.webp",
      },
      {
        id: 11,
        producto: "Clavel Blanco",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 73,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CLAVEL BLANCO 13 OCTUBRE 2022.webp",
      },
      {
        id: 12,
        producto: "Clavel Mix Claro",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 76,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CLAVEL MIX CLARO 27 FEB 2019.webp",
      },
      {
        id: 13,
        producto: "Clavel Mix Oscuro",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 77,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CLAVEL MIX OSCURO 05 MAYO 2022.webp",
      },
      {
        id: 14,
        producto: "Clavel Rojo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 78,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/CLAVEL ROJO MARZO 2023.webp",
      },
      {
        id: 15,
        producto: "Coleus Variados",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 83,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/COLEUS DIC 2020.webp",
      },
      {
        id: 16,
        producto: "Cosmos variados",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 91,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/COSMOS VARIADOS 18AGOSTO 2022.webp",
      },
      {
        id: 17,
        producto: "Crisantemo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 92,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/CRISANTEMO 18AGOSTO 2022.webp",
      },
      {
        id: 18,
        producto: "Delphinium",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 93,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/DELPHINIUM ENERO 2024.webp",
      },
      {
        id: 19,
        producto: "Digital",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 94,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/DIGITAL 18AGOSTO 2022.webp",
      },
      {
        id: 20,
        producto: "Estatice Amarillo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 105,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ESTATICE AMARILLA.webp",
      },
      {
        id: 21,
        producto: "Estatice Azul",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 108,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ESTATICE AZUL.webp",
      },
      {
        id: 22,
        producto: "Estatice Blanco",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 111,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ESTATICE BLANCA.webp",
      },
      {
        id: 23,
        producto: "Estatice Mix",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 114,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ESTATICE MIX.webp",
      },
      {
        id: 24,
        producto: "Estatice Rojo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 120,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/ESTATICE ROJA 05 MAYO 2022.webp",
      },
      {
        id: 25,
        producto: "Estrelicia",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 126,
        precio: 37.0,
        imagen:
          "../assets/categorias/ornamentales/ESTRELICIA 18AGOSTO 2022.webp",
      },
      {
        id: 26,
        producto: "Flores Anuales",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 127,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/FLORES ANUALES 29JUNIO 2022.webp",
      },
      {
        id: 27,
        producto: "Flox",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 128,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/FLOX 29 AGOSTO 2019.webp",
      },
      {
        id: 28,
        producto: "Gerbera",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 131,
        precio: 37.0,
        imagen:
          "../assets/categorias/ornamentales/GERBERA 13 OCTUBRE 2022.webp",
      },
      {
        id: 29,
        producto: "Gipsophilia",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 132,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/GIPSOPHILIA.webp",
      },
      {
        id: 30,
        producto: "Girasol",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 142,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/GIRASOL ENERO 2024.webp",
      },
      {
        id: 31,
        producto: "Girasol de Centro",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 143,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/GIRASOL DE CENTRO.webp",
      },
      {
        id: 32,
        producto: "Guisantes de Olor",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 151,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/GUISANTES DE OLOR DIC 2020.webp",
      },
      {
        id: 33,
        producto: "Ipomea V",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 164,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/IPOMEA VARIADA.webp",
      },
      {
        id: 34,
        producto: "Margarita botoncitos",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 180,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/MARGARITA BOTONCITOS.webp",
      },
      {
        id: 35,
        producto: "Margarita Gigante",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 181,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/MARGARITA GIGANTE 5JUNIO2023.webp",
      },
      {
        id: 36,
        producto: "Miosotis de los Alpes",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 190,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/MIOSOTIS 18AGOSTO 2022.webp",
      },
      {
        id: 37,
        producto: "Miramelindo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 191,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/MIRAMELINDO 18AGOSTO 2022.webp",
      },
      {
        id: 38,
        producto: "Mix de flores para abejas y otros insectos beneficos",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 406,
        precio: 37.0,
        imagen:
          "../assets/categorias/ornamentales/MEZCLA DE FLORES PARA ABEJAS.webp",
      },
      {
        id: 39,
        producto: "Pensamiento Amarillo",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 196,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/PENSAMIENTO AMARILLO 30 MARZO 2022.webp",
      },
      {
        id: 40,
        producto: "Pensamiento Azul",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 197,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/PENSAMIENTO AZUL 29JUNIO 2022.webp",
      },
      {
        id: 41,
        producto: "Pensamiento Mix",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 200,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/PENSAMIENTO MIX.webp",
      },
      {
        id: 42,
        producto: "Petunia Colgante",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 212,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/PETUNIA COLGANTE 03 DICIEMBRE 2021.webp",
      },
      {
        id: 43,
        producto: "Petunia Grande",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 213,
        precio: 37.0,
        imagen:
          "../assets/categorias/ornamentales/PETUNIA GRANDE 29JUNIO 2022.webp",
      },
      {
        id: 44,
        producto: "Petunia Grandiflora",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 214,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/PETUNIA GRANDIFLORA 02 JUNIO 2021.webp",
      },
      {
        id: 45,
        producto: "Pimiento Ornamental",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 221,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/PIMIENTO ORNAMENTAL DIC 2020.webp",
      },
      {
        id: 46,
        producto: "Reina Marg. Belleza",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 243,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/REINA MARGARITA BELLEZA 29JUNIO 2022.webp",
      },
      {
        id: 47,
        producto: "Reina Marg. Mix",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 241,
        precio: 22.0,
        imagen:
          "../assets/categorias/ornamentales/REINA MARGARITA MIX 29JUNIO 2022.webp",
      },
      {
        id: 48,
        producto: "Siempreviva",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 270,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/SIEMPREVIVA.webp",
      },
      {
        id: 49,
        producto: "Thuja",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 430,
        precio: 37.0,
        imagen: "../assets/categorias/ornamentales/THUJA 24 ABRIL 2023.webp",
      },
      {
        id: 50,
        producto: "Verdolaga",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 284,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/VERDOLAGA 05 MAYO 2022.webp",
      },
      {
        id: 51,
        producto: "Violeta",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 285,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/VIOLETA MARZO 2023.webp",
      },
      {
        id: 52,
        producto: "Zinnia",
        codigo_de_barras: "#¡DESCONOCIDO!",
        codigo: 291,
        precio: 22.0,
        imagen: "../assets/categorias/ornamentales/ZINNIA MARZO 2023.webp",
      },
    ],

    sustratos: [
      {
        id: 1,
        nombre: "SUSTRATO P/GERMINAR SEMILLAS",
        codigo_de_barras: "#¡VALOR!",
        codigo: 339,
        precio: 35.0,
        imagen:
          "../assets/categorias/sustratos/SUSTRATO PARA GERMINAR SEMILLAS.webp",
      },
      {
        id: 2,
        nombre: "SUSTRATO P/CACTUS",
        codigo_de_barras: "#¡VALOR!",
        codigo: 375,
        precio: 30.0,
        imagen: "../assets/categorias/sustratos/CACTUS Y SUCULENTAS_.webp",
      },
      {
        id: 3,
        nombre: "SUSTRATO P/CACTUS BOLSA PEQUEÑA",
        codigo_de_barras: "#¡VALOR!",
        codigo: 436,
        precio: 6.0,
        imagen: "../assets/categorias/sustratos/CACTUS Y SUCULENTAS_.webp",
      },
      {
        id: 4,
        nombre: "SUSTRATO P/ORQUIDEAS",
        codigo_de_barras: "#¡VALOR!",
        codigo: 376,
        precio: 35.0,
        imagen: "../assets/categorias/sustratos/ORQUIDEAS.webp",
      },
      {
        id: 5,
        nombre: "SUSTRATO P/ORQUIDEAS BOLSA PEQUEÑA",
        codigo_de_barras: "#¡VALOR!",
        codigo: 405,
        precio: 6.0,
        imagen: "../assets/categorias/sustratos/ORQUIDEAS.webp",
      },
      {
        id: 6,
        nombre: "SUSTRATO BOCASHI",
        codigo_de_barras: "#¡VALOR!",
        codigo: 391,
        precio: 50.0,
        imagen: "../assets/categorias/sustratos/BOCASHI.webp",
      },
      {
        id: 7,
        nombre: "MIX DE GRAVA ORNAMENTAL-FINA",
        codigo_de_barras: "#¡VALOR!",
        codigo: 415,
        precio: 25.0,
        imagen: "../assets/categorias/sustratos/GRAVA ORNAMENTAL FINA.webp",
      },
    ],
  },
];
export default categorias;
